# Generated by Django 6.0.7 on 2026-07-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The main way a student might phrase this question', max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('admission', 'Admission'), ('fees', 'Fees'), ('hostel', 'Hostel'), ('general', 'General')], default='general', max_length=20)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated alternate phrasings/keywords', max_length=500)),
            ],
        ),
    ]
