# Generated by Django 6.0.7 on 2026-07-20 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusbot', '0004_chatsession_updated_at_alter_chatsession_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnansweredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('times_asked', models.PositiveIntegerField(default=1)),
                ('is_resolved', models.BooleanField(default=False, help_text='Tick this once the question has been added to the FAQ table')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_asked_at', models.DateTimeField(auto_now=True)),
                ('asked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unanswered_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_asked_at'],
            },
        ),
    ]
